//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino.EntityDataModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasinoDB
    {
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string UniqueId { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<decimal> BloackedAmount { get; set; }
        public string IdPoof { get; set; }
    }
}
